const title = document.querySelector(".club_title");
setTimeout(() => { title.textContent = "6####" }, 100);
setTimeout(() => { title.textContent = "60###" }, 200);
setTimeout(() => { title.textContent = "600##" }, 300);
setTimeout(() => { title.textContent = "6003#" }, 500);
setTimeout(() => { title.textContent = "C003#" }, 800);
setTimeout(() => { title.textContent = "CO03#" }, 1300);
setTimeout(() => { title.textContent = "COD3#" }, 2100);
setTimeout(() => { title.textContent = "CODE#" }, 3400);
setTimeout(() => { title.textContent = "CODEX" }, 5500);