// const title = document.querySelector(".club_title");
// setTimeout(() => { title.textContent = "6####" }, 200);
// setTimeout(() => { title.textContent = "60###" }, 400);
// setTimeout(() => { title.textContent = "600##" }, 600);
// setTimeout(() => { title.textContent = "6003#" }, 800);
// setTimeout(() => { title.textContent = "C003#" }, 1000);
// setTimeout(() => { title.textContent = "CO03#" }, 1200);
// setTimeout(() => { title.textContent = "COD3#" }, 1400);
// setTimeout(() => { title.textContent = "CODE#" }, 1600);
// setTimeout(() => { title.textContent = "CODEX" }, 1800);